openapi: 3.0.0
info:
  title: Test API for GSoC project
  version: "1.0.0"
  description: |
    This is a OpenAPI description for testing my GSoC project. The name of the path defines what
    will be tested and the operation object will be set accordingly.
    Structure of tests:
    /testParameter*   --> To test everything related to path/query parameteres
    /testResponse*    --> To test everything related to respones
    /testRequestBody* --> To test everything related to request bodies
    others            --> Other stuff

paths:
  ########################## RESPONSE ##########################
  /testResponseNative:
    get:
      operationId: testResponseNative
      # TODO: Due to https://github.com/googleapis/gnostic-grpc/pull/12 this response won't get rendered any more. Fix this if someone complains
      responses:
        200:
          description: succes
          content:
            application/json:
              schema:
                type: string
  /testResponseReference:
    get:
      operationId: testResponseReference
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /testResponseMultipleContent:
    get:
      operationId: testResponseMultipleContent
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
            application/xml:
              schema:
                $ref: '#/components/schemas/Person'
        400:
          description: failure
  /testResponse400StatusCode:
    get:
      operationId: testResponse400StatusCode
      responses:
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /testResponseComponentReference:
    get:
      operationId: testResponseComponentReference
      responses:
        200:
          $ref: '#/components/responses/Response'
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      type: object
    Person:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        age:
          type: integer
          format: int64
        name:
          type: string
          example: Peter
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
  responses:
    Response:
      description: success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Person'
