openapi: 3.0.0
info:
  title: Test API for GSoC project
  version: "1.0.0"
  description: |
    A cyclic dependency between cyclic_dependency_1.yaml <--> cyclic_dependency_2.yaml. jhumps's protoreflect can't
    print cyclic dependency files. The method 'CreateFileDescriptorFromSet' inside renderer.go throws an error. As far
    as I can tell gnostic-grpc is working correctly for cyclic dependencies.
paths:
  /testCyclicDependency:
    get:
      operationId: testCyclicDependency
      responses:
        200:
          $ref: https://raw.githubusercontent.com/googleapis/gnostic-grpc/master/generator/testfiles/errors/cyclic_dependency_2.yaml#/components/responses/Response
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
        age:
          type: integer
          format: int64