name: Go

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Get protobuf-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
        # until google/gnostic release new version
        go install github.com/google/gnostic@v0.5.6-0.20210930170106-c7a5e4fe8b37
  
    - name: Compile Protos
      run: |
        ./COMPILE-PROTOS.sh
     
    - name: Run Test
      run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
    
    - name: Run bash
      run: bash <(curl -s https://codecov.io/bash)
