name: Go

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Get protobuf-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        protoc --version
        # until google/gnostic release new version
        go install github.com/google/gnostic@v0.6.8
  
    - name: Compile Protos
      run: |
        ./COMPILE-PROTOS.sh
     
    - name: Run Test
      run: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
    
    - name: Run bash
      run: bash <(curl -s https://codecov.io/bash)